# Linear Algebra for CpE
## Laboratory 7 : Matrix Operations

Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more.

### Objectives
At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intemrediate equations.
3. Apply matrix algebra in engineering solutions.

## Discussion

In [37]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for a matrix $A$ its transpose is denoted as $A^T$. So for example:

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}$$

This can now be achieved programmatically by using `np.transpose()` or using the `T` method.

In [3]:
A = np.array([
    [1 ,2, 5],
    [5, -1, 0],
    [0, -3, 3]
])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [7]:
AT1 = np.transpose(A)

In [8]:
AT2 = A.T

In [9]:
np.array_equiv(AT1, AT2)

True

In [12]:
B = np.array([
    [1,2,3,4],
    [1,0,2,1],
])
B.shape

(2, 4)

In [13]:
np.transpose(B).shape

(4, 2)

In [14]:
B.T.shape

(4, 2)

#### Try to create your own matrix (you can try non-squares) to test transposition.

In [ ]:
## Try out your code here.

## Dot Product / Inner Product

If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [15]:
X = np.array([
    [1,2],
    [0,1]
])
Y = np.array([
    [-1,0],
    [2,2]
])

In [16]:
np.dot(X,Y)

array([[3, 4],
       [2, 2]])

In [17]:
X.dot(Y)

array([[3, 4],
       [2, 2]])

In [18]:
X @ Y

array([[3, 4],
       [2, 2]])

In [19]:
np.matmul(X,Y)

array([[3, 4],
       [2, 2]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [20]:
A = np.array([
    [2, 4],
    [5, -2],
    [0, 1]
])
B = np.array([
    [1,1],
    [3,3],
    [-1,-2]
])
C = np.array([
    [0,1,1],
    [1,1,2]
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 2)
(3, 2)
(2, 3)


In [21]:
A @ C

array([[ 4,  6, 10],
       [-2,  3,  1],
       [ 1,  1,  2]])

In [22]:
B @ C

array([[ 1,  2,  3],
       [ 3,  6,  9],
       [-2, -3, -5]])

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [24]:
A @ B.T

array([[  6,  18, -10],
       [  3,   9,  -1],
       [  1,   3,  -2]])

In [27]:
X = np.array([
    [1,2,3,0]
])
Y = np.array([
    [1,0,4,-1]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [30]:
Y.T @ X

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

And youcan see that when you try to multiply A and B, it returns `ValueError` pertaining to matrix shape mismatch.

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

I'll be doing just one of the properties and I'll leave the rest to test your skills!

In [32]:
A = np.array([
    [3,2,1],
    [4,5,1],
    [1,1,0]
])
B = np.array([
    [4,1,6],
    [4,1,9],
    [1,4,8]
])
C = np.array([
    [1,1,0],
    [0,1,1],
    [1,0,1]
])

In [33]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [57]:
np.array_equal(a_dot_z,z_mat)

True

In [66]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

## Determinant

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [67]:
A = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(A)

3.0000000000000004

In [68]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)

-235.0

## Inverse

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [75]:
M = np.array([
    [1,7],
    [-3, 5]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [77]:
## And now let's test your skills in solving a matrix with high dimensions:
N = np.array([
    [18,5,23,1,0,33,5],
    [0,45,0,11,2,4,2],
    [5,9,20,0,0,0,3],
    [1,6,4,4,8,43,1],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [ ]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade


## Activity

### Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [36]:
#Matrices
X = np.array([
    [9, 3, 7],
    [4, 8, 1],
    [4, 6, 3]
])

Y = np.array([
    [-2 ,4, 6],
    [4, 8, 9],
    [2, -1, 5]
])

Z = np.array([
    [0 ,2, 7],
    [5, 2, 1],
    [2, 7, 2]
])


#### Property 1. $A\cdot(B+C) = A\cdot B + A\cdot C$

In [13]:
#Function in X dot Y
#first row of matrix
xy_zero_by_zero_element = ((X[0,0] * Y[0,0])+(X[0,1] * Y[1,0])+(X[0,2]*Y[2,0]))

xy_zero_by_one_element = ((X[0,0] * Y[0,1])+(X[0,1] * Y[1,1])+(X[0,2]*Y[2,1]))

xy_zero_by_two_element = ((X[0,0] * Y[0,2])+(X[0,1] * Y[1,2])+(X[0,2]*Y[2,2]))


#second row of matrix 
xy_one_by_zero_element = ((X[1,0] * Y[0,0])+(X[1,1] * Y[1,0])+(X[1,2]*Y[2,0]))

xy_one_by_one_element = ((X[1,0] * Y[0,1])+(X[1,1] * Y[1,1])+(X[1,2]*Y[2,1]))

xy_one_by_two_element = ((X[1,0] * Y[0,2])+(X[1,1] * Y[1,2])+(X[1,2]*Y[2,2]))


#third row of matrix
xy_two_by_zero_element = ((X[2,0] * Y[0,0])+(X[2,1] * Y[1,0])+(X[2,2]*Y[2,0]))

xy_two_by_one_element = ((X[2,0] * Y[0,1])+(X[2,1] * Y[1,1])+(X[2,2]*Y[2,1]))

xy_two_by_two_element = ((X[2,0] * Y[0,2])+(X[2,1] * Y[1,2])+(X[2,2]*Y[2,2]))


print(f'The product of X and Y are:\n [{[xy_zero_by_zero_element, xy_zero_by_one_element, xy_zero_by_two_element]},\n {[xy_one_by_zero_element, xy_one_by_one_element, xy_one_by_two_element]},\n {[xy_two_by_zero_element, xy_two_by_one_element, xy_two_by_two_element]}]')

The product of X and Y are:
 [[8, 53, 116],
 [26, 79, 101],
 [22, 61, 93]]


In [14]:
np.dot(X,Y)

array([[  8,  53, 116],
       [ 26,  79, 101],
       [ 22,  61,  93]])

In [15]:
#Function in Y dot X
#first row of matrix
yx_zero_by_zero_element = ((Y[0,0] * X[0,0])+(Y[0,1] * X[1,0])+(Y[0,2]*X[2,0]))

yx_zero_by_one_element = ((Y[0,0] * X[0,1])+(Y[0,1] * X[1,1])+(Y[0,2]*X[2,1]))

yx_zero_by_two_element = ((Y[0,0] * X[0,2])+(Y[0,1] * X[1,2])+(Y[0,2]*X[2,2]))

#second row of matrix 
yx_one_by_zero_element = ((Y[1,0] * X[0,0])+(Y[1,1] * X[1,0])+(Y[1,2]*X[2,0]))

yx_one_by_one_element = ((Y[1,0] * X[0,1])+(Y[1,1] * X[1,1])+(Y[1,2]*X[2,1]))

yx_one_by_two_element = ((Y[1,0] * X[0,2])+(Y[1,1] * X[1,2])+(Y[1,2]*X[2,2]))

#third row of matrix
yx_two_by_zero_element = ((Y[2,0] * X[0,0])+(Y[2,1] * X[1,0])+(Y[2,2]*X[2,0]))

yx_two_by_one_element = ((Y[2,0] * X[0,1])+(Y[2,1] * X[1,1])+(Y[2,2]*X[2,1]))

yx_two_by_two_element = ((Y[2,0] * X[0,2])+(Y[2,1] * X[1,2])+(Y[2,2]*X[2,2]))


print(f'The product of X and Y are:\n [{[yx_zero_by_zero_element, yx_zero_by_one_element, yx_zero_by_two_element]},\n {[yx_one_by_zero_element, yx_one_by_one_element, yx_one_by_two_element]},\n {[yx_two_by_zero_element, yx_two_by_one_element, yx_two_by_two_element]}]')

The product of X and Y are:
 [[22, 62, 8],
 [104, 130, 63],
 [34, 28, 28]]


In [16]:
np.dot(X,Y)

array([[  8,  53, 116],
       [ 26,  79, 101],
       [ 22,  61,  93]])

In [17]:
np.dot(X,Y) == np.dot(Y,X)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

#### Property 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$

In [18]:
#Function in X dot (Y dot Z)
#first row of array 
yzx_zero_by_zero_element = ((xy_zero_by_zero_element * Z[0,0])+(xy_zero_by_one_element * Z[1,0])+(xy_zero_by_two_element *Z[2,0]))

yzx_zero_by_one_element = ((xy_zero_by_zero_element * Z[0,1])+(xy_zero_by_one_element * Z[1,1])+(xy_zero_by_two_element *Z[2,1]))

yzx_zero_by_two_element = ((xy_zero_by_zero_element * Z[0,2])+(xy_zero_by_one_element  * Z[1,2])+(xy_zero_by_two_element *Z[2,2]))

#second row of array 
yzx_one_by_zero_element = ((xy_one_by_zero_element * Z[0,0])+(xy_one_by_one_element * Z[1,0])+(xy_one_by_two_element *Z[2,0]))

yzx_one_by_one_element = ((xy_one_by_zero_element * Z[0,1])+(xy_one_by_one_element * Z[1,1])+(xy_one_by_two_element *Z[2,1]))

yzx_one_by_two_element = ((xy_one_by_zero_element * Z[0,2])+(xy_one_by_one_element * Z[1,2])+(xy_one_by_two_element *Z[2,2]))


#third row of array
yzx_two_by_zero_element = ((xy_two_by_zero_element * Z[0,0])+(xy_two_by_one_element * Z[1,0])+(xy_two_by_two_element *Z[2,0]))

yzx_two_by_one_element = ((xy_two_by_zero_element * Z[0,1])+(xy_two_by_one_element * Z[1,1])+(xy_two_by_two_element *Z[2,1]))

yzx_two_by_two_element = ((xy_two_by_zero_element * Z[0,2])+(xy_two_by_one_element * Z[1,2])+(xy_two_by_two_element *Z[2,2]))


print(f'The product of X and Y are:\n [{[yzx_zero_by_zero_element, yzx_zero_by_one_element, yzx_zero_by_two_element]},\n {[yzx_one_by_zero_element, yzx_one_by_one_element, yzx_one_by_two_element]},\n {[yzx_two_by_zero_element, yzx_two_by_one_element, yzx_two_by_two_element]}]')

The product of X and Y are:
 [[497, 934, 341],
 [597, 917, 463],
 [491, 817, 401]]


In [19]:
X @ (Y @ Z)

array([[497, 934, 341],
       [597, 917, 463],
       [491, 817, 401]])

In [21]:
#Function in X dot (Y dot Z)
#first row of array 
xyz_zero_by_zero_element = ((xy_zero_by_zero_element * Z[0,0])+(xy_zero_by_one_element * Z[1,0])+(xy_zero_by_two_element *Z[2,0]))

xyz_zero_by_one_element = ((xy_zero_by_zero_element * Z[0,1])+(xy_zero_by_one_element * Z[1,1])+(xy_zero_by_two_element *Z[2,1]))

xyz_zero_by_two_element = ((xy_zero_by_zero_element * Z[0,2])+(xy_zero_by_one_element  * Z[1,2])+(xy_zero_by_two_element *Z[2,2]))

#second row of array 
xyz_one_by_zero_element = ((xy_one_by_zero_element * Z[0,0])+(xy_one_by_one_element * Z[1,0])+(xy_one_by_two_element *Z[2,0]))

xyz_one_by_one_element = ((xy_one_by_zero_element * Z[0,1])+(xy_one_by_one_element * Z[1,1])+(xy_one_by_two_element *Z[2,1]))

xyz_one_by_two_element = ((xy_one_by_zero_element * Z[0,2])+(xy_one_by_one_element * Z[1,2])+(xy_one_by_two_element *Z[2,2]))


#third row of array
xyz_two_by_zero_element = ((xy_two_by_zero_element * Z[0,0])+(xy_two_by_one_element * Z[1,0])+(xy_two_by_two_element *Z[2,0]))

xyz_two_by_one_element = ((xy_two_by_zero_element * Z[0,1])+(xy_two_by_one_element * Z[1,1])+(xy_two_by_two_element *Z[2,1]))

xyz_two_by_two_element = ((xy_two_by_zero_element * Z[0,2])+(xy_two_by_one_element * Z[1,2])+(xy_two_by_two_element *Z[2,2]))


print(f'The product of X and Y are:\n [{[xyz_zero_by_zero_element, xyz_zero_by_one_element, xyz_zero_by_two_element]},\n {[xyz_one_by_zero_element, xyz_one_by_one_element, xyz_one_by_two_element]},\n {[xyz_two_by_zero_element, xyz_two_by_one_element, xyz_two_by_two_element]}]')

The product of X and Y are:
 [[497, 934, 341],
 [597, 917, 463],
 [491, 817, 401]]


In [22]:
(X @ Y) @ Z

array([[497, 934, 341],
       [597, 917, 463],
       [491, 817, 401]])

In [23]:
X @ (Y @ Z) == (X @ Y) @ Z

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#### Property 3. $A\cdot(B+C) = A\cdot B + A\cdot C$

In [30]:
V = Y+Z
print(f'The sum of Y and Z are:\n{V}')

#first row of array 
xv_zero_by_zero_element = ((X[0,0] * V[0,0])+(X[0,1] * V[1,0])+(X[0,2]*V[2,0]))

xv_zero_by_one_element = ((X[0,0] * V[0,1])+(X[0,1] * V[1,1])+(X[0,2]*V[2,1]))

xv_zero_by_two_element = ((X[0,0] * V[0,2])+(X[0,1] * V[1,2])+(X[0,2]*V[2,2]))


#second row of array 
xv_one_by_zero_element = ((X[1,0] * V[0,0])+(X[1,1] * V[1,0])+(X[1,2]*V[2,0]))

xv_one_by_one_element = ((X[1,0] * V[0,1])+(X[1,1] * V[1,1])+(X[1,2]*V[2,1]))

xv_one_by_two_element = ((X[1,0] * V[0,2])+(X[1,1] * V[1,2])+(X[1,2]*V[2,2]))


#third row of array
xv_two_by_zero_element = ((X[2,0] * V[0,0])+(X[2,1] * V[1,0])+(X[2,2]*V[2,0]))

xv_two_by_one_element = ((X[2,0] * V[0,1])+(X[2,1] * V[1,1])+(X[2,2]*V[2,1]))

xv_two_by_two_element = ((X[2,0] * V[0,2])+(X[2,1] * V[1,2])+(X[2,2]*V[2,2]))


print(f'The product of X and V are:\n [{[xv_zero_by_zero_element, xv_zero_by_one_element, xv_zero_by_two_element]},\n {[xv_one_by_zero_element, xv_one_by_one_element, xv_one_by_two_element]},\n {[xv_two_by_zero_element, xv_two_by_one_element, xv_two_by_two_element]}]')

The sum of Y and Z are:
[[-2  6 13]
 [ 9 10 10]
 [ 4  6  7]]
The product of X and V are:
 [[37, 126, 196],
 [68, 110, 139],
 [58, 102, 133]]


In [25]:
X @ (Y+Z)

array([[ 37, 126, 196],
       [ 68, 110, 139],
       [ 58, 102, 133]])

In [31]:
#Product of X and Y 
#first row of array 
xy_zero_by_zero_element = ((X[0,0] * Y[0,0])+(X[0,1] * Y[1,0])+(X[0,2]*Y[2,0]))

xy_zero_by_one_element = ((X[0,0] * Y[0,1])+(X[0,1] * Y[1,1])+(X[0,2]*Y[2,1]))

xy_zero_by_two_element = ((X[0,0] * Y[0,2])+(X[0,1] * Y[1,2])+(X[0,2]*Y[2,2]))


#second row of array 
xy_one_by_zero_element = ((X[1,0] * Y[0,0])+(X[1,1] * Y[1,0])+(X[1,2]*Y[2,0]))

xy_one_by_one_element = ((X[1,0] * Y[0,1])+(X[1,1] * Y[1,1])+(X[1,2]*Y[2,1]))

xy_one_by_two_element = ((X[1,0] * Y[0,2])+(X[1,1] * Y[1,2])+(X[1,2]*Y[2,2]))


#third row of array
xy_two_by_zero_element = ((X[2,0] * Y[0,0])+(X[2,1] * Y[1,0])+(X[2,2]*Y[2,0]))

xy_two_by_one_element = ((X[2,0] * Y[0,1])+(X[2,1] * Y[1,1])+(X[2,2]*Y[2,1]))

xy_two_by_two_element = ((X[2,0] * Y[0,2])+(X[2,1] * Y[1,2])+(X[2,2]*Y[2,2]))

print(f'The product of X and Y are:\n [{[xy_zero_by_zero_element, xy_zero_by_one_element, xy_zero_by_two_element]},\n {[xy_one_by_zero_element, xy_one_by_one_element, xy_one_by_two_element]},\n {[xy_two_by_zero_element, xy_two_by_one_element, xy_two_by_two_element]}]')

#Product of X and Z
#first row of array 
xz_zero_by_zero_element = ((X[0,0] * Z[0,0])+(X[0,1] * Z[1,0])+(X[0,2]*Z[2,0]))

xz_zero_by_one_element = ((X[0,0] * Z[0,1])+(X[0,1] * Z[1,1])+(X[0,2]*Z[2,1]))

xz_zero_by_two_element = ((X[0,0] * Z[0,2])+(X[0,1] * Z[1,2])+(X[0,2]*Z[2,2]))


#second row of array 
xz_one_by_zero_element = ((X[1,0] * Z[0,0])+(X[1,1] * Z[1,0])+(X[1,2]*Z[2,0]))

xz_one_by_one_element = ((X[1,0] * Z[0,1])+(X[1,1] * Z[1,1])+(X[1,2]*Z[2,1]))

xz_one_by_two_element = ((X[1,0] * Z[0,2])+(X[1,1] * Z[1,2])+(X[1,2]*Z[2,2]))


#third row of array
xz_two_by_zero_element = ((X[2,0] * Z[0,0])+(X[2,1] * Z[1,0])+(X[2,2]*Z[2,0]))

xz_two_by_one_element = ((X[2,0] * Z[0,1])+(X[2,1] * Z[1,1])+(X[2,2]*Z[2,1]))

xz_two_by_two_element = ((X[2,0] * Z[0,2])+(X[2,1] * Z[1,2])+(X[2,2]*Z[2,2]))


print(f'The product of X and Z are:\n [{[xz_zero_by_zero_element, xz_zero_by_one_element, xz_zero_by_two_element]},\n {[xz_one_by_zero_element, xz_one_by_one_element, xz_one_by_two_element]},\n {[xz_two_by_zero_element, xz_two_by_one_element, xz_two_by_two_element]}]')

#For the sum
sum_one = xy_zero_by_zero_element + xz_zero_by_zero_element
sum_two = xy_zero_by_one_element + xz_zero_by_one_element
sum_three = xy_zero_by_two_element + xz_zero_by_two_element
sum_four = xy_one_by_zero_element + xz_one_by_zero_element
sum_five = xy_one_by_one_element + xz_one_by_one_element
sum_six = xy_one_by_two_element + xz_one_by_two_element
sum_seven = xy_two_by_zero_element + xz_two_by_zero_element
sum_eight = xy_two_by_one_element + xz_two_by_one_element
sum_nine = xy_two_by_one_element + xz_two_by_two_element

print(f'Overall are:\n [{[sum_one, sum_two, sum_three]},\n {[sum_four, sum_five, sum_six]},\n {[sum_seven, sum_eight, sum_nine]}]')

The product of X and Y are:
 [[8, 53, 116],
 [26, 79, 101],
 [22, 61, 93]]
The product of X and Z are:
 [[29, 73, 80],
 [42, 31, 38],
 [36, 41, 40]]
Overall are:
 [[37, 126, 196],
 [68, 110, 139],
 [58, 102, 101]]


In [27]:
X@Y + X@Z

array([[ 37, 126, 196],
       [ 68, 110, 139],
       [ 58, 102, 133]])

In [28]:
(X @ (Y+Z)) == (X@Y + X@Z)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#### Property 4. $(B+C)\cdot A = B\cdot A + C\cdot A$

In [32]:
W = Y+Z
print(f'The sum of Y and Z are:\n{V}')

#first row of array 
wx_zero_by_zero_element = ((W[0,0] * X[0,0])+(Z[0,1] * X[1,0])+(W[0,2]*X[2,0]))

wx_zero_by_one_element = ((W[0,0] * X[0,1])+(Z[0,1] * X[1,1])+(W[0,2]*X[2,1]))

wx_zero_by_two_element = ((W[0,0] * X[0,2])+(Z[0,1] * X[1,2])+(W[0,2]*X[2,2]))


#second row of array 
wx_one_by_zero_element = ((W[1,0] * X[0,0])+(Z[1,1] * X[1,0])+(W[1,2]*X[2,0]))

wx_one_by_one_element = ((W[1,0] * X[0,1])+(Z[1,1] * X[1,1])+(W[1,2]*X[2,1]))

wx_one_by_two_element = ((W[1,0] * X[0,2])+(Z[1,1] * X[1,2])+(W[1,2]*X[2,2]))


#third row of array
wx_two_by_zero_element = ((W[2,0] * X[0,0])+(Z[2,1] * X[1,0])+(Z[2,2]*X[2,0]))

wx_two_by_one_element = ((W[2,0] * X[0,1])+(Z[2,1] * X[1,1])+(Z[2,2]*X[2,1]))

wx_two_by_two_element = ((W[2,0] * X[0,2])+(Z[2,1] * X[1,2])+(Z[2,2]*X[2,2]))


print(f'The product of W and x are:\n [{[wx_zero_by_zero_element, wx_zero_by_one_element, wx_zero_by_two_element]},\n {[wx_one_by_zero_element, wx_one_by_one_element, wx_one_by_two_element]},\n {[wx_two_by_zero_element, wx_two_by_one_element, wx_two_by_two_element]}]')

The sum of Y and Z are:
[[-2  6 13]
 [ 9 10 10]
 [ 4  6  7]]
The product of W and x are:
 [[42, 88, 27],
 [129, 103, 95],
 [72, 80, 41]]


In [33]:
(Y+Z) @ X

array([[ 58, 120,  31],
       [161, 167, 103],
       [ 88, 102,  55]])

In [39]:
#Product of Y and X 
#first row of array 
yx_zero_by_zero_element = ((Y[0,0] * X[0,0])+(Y[0,1] * X[1,0])+(Y[0,2]*X[2,0]))

yx_zero_by_one_element = ((Y[0,0] * X[0,1])+(X[0,1] * X[1,1])+(Y[0,2]*X[2,1]))

yx_zero_by_two_element = ((Y[0,0] * X[0,2])+(X[0,1] * X[1,2])+(Y[0,2]*X[2,2]))


#second row of array 
yx_one_by_zero_element = ((Y[1,0] * X[0,0])+(Y[1,1] * X[1,0])+(Y[1,2]*X[2,0]))

yx_one_by_one_element = ((Y[1,0] * X[0,1])+(Y[1,1] * X[1,1])+(Y[1,2]*X[2,1]))

yx_one_by_two_element = ((Y[1,0] * X[0,2])+(Y[1,1] * X[1,2])+(Y[1,2]*X[2,2]))


#third row of array
yx_two_by_zero_element = ((Y[2,0] * X[0,0])+(Y[2,1] * X[1,0])+(Y[2,2]*X[2,0]))

yx_two_by_one_element = ((Y[2,0] * X[0,1])+(Y[2,1] * X[1,1])+(Y[2,2]*X[2,1]))

yx_two_by_two_element = ((Y[2,0] * X[0,2])+(Y[2,1] * X[1,2])+(Y[2,2]*X[2,2]))

print(f'The product of Y and X are:\n [{[yx_zero_by_zero_element, yx_zero_by_one_element, yx_zero_by_two_element]},\n {[yx_one_by_zero_element, yx_one_by_one_element, yx_one_by_two_element]},\n {[yx_two_by_zero_element, yx_two_by_one_element, yx_two_by_two_element]}]')

#Product of Z and X
#first row of array 
zx_zero_by_zero_element = ((Z[0,0] * X[0,0])+(Z[0,1] * X[1,0])+(Z[0,2]*X[2,0]))

zx_zero_by_one_element = ((Z[0,0] * X[0,1])+(Z[0,1] * X[1,1])+(Z[0,2]*X[2,1]))

zx_zero_by_two_element = ((Z[0,0] * X[0,2])+(Z[0,1] * X[1,2])+(Z[0,2]*X[2,2]))


#second row of array 
zx_one_by_zero_element = ((Z[1,0] * X[0,0])+(Z[1,1] * X[1,0])+(Z[1,2]*X[2,0]))

zx_one_by_one_element = ((Z[1,0] * X[0,1])+(Z[1,1] * X[1,1])+(Z[1,2]*X[2,1]))

zx_one_by_two_element = ((Z[1,0] * X[0,2])+(Z[1,1] * X[1,2])+(Z[1,2]*X[2,2]))


#third row of array
zx_two_by_zero_element = ((Z[2,0] * X[0,0])+(Z[2,1] * X[1,0])+(Z[2,2]*X[2,0]))

zx_two_by_one_element = ((Z[2,0] * X[0,1])+(Z[2,1] * X[1,1])+(Z[2,2]*X[2,1]))

zx_two_by_two_element = ((Z[2,0] * X[0,2])+(Z[2,1] * X[1,2])+(Z[2,2]*X[2,2]))


print(f'The product of Z and X are:\n [{[zx_zero_by_zero_element, zx_zero_by_one_element, zx_zero_by_two_element]},\n {[zx_one_by_zero_element, zx_one_by_one_element, zx_one_by_two_element]},\n {[zx_two_by_zero_element, zx_two_by_one_element, zx_two_by_two_element]}]')

#For the sum
sum_one = yx_zero_by_zero_element + zx_zero_by_zero_element
sum_two = yx_zero_by_one_element + xz_zero_by_one_element
sum_three = yx_zero_by_two_element + zx_zero_by_two_element
sum_four = yx_one_by_zero_element + zx_one_by_zero_element
sum_five = yx_one_by_one_element + zx_one_by_one_element
sum_six = yx_one_by_two_element + zx_one_by_two_element
sum_seven = yx_two_by_zero_element + zx_two_by_zero_element
sum_eight = yx_two_by_one_element + zx_two_by_one_element
sum_nine = yx_two_by_one_element + zx_two_by_two_element

print(f'Overall are:\n [{[sum_one, sum_two, sum_three]},\n {[sum_four, sum_five, sum_six]},\n {[sum_seven, sum_eight, sum_nine]}]')

The product of Y and X are:
 [[22, 54, 7],
 [104, 130, 63],
 [34, 28, 28]]
The product of Z and X are:
 [[36, 58, 23],
 [57, 37, 40],
 [54, 74, 27]]
Overall are:
 [[58, 112, 30],
 [161, 167, 103],
 [88, 102, 55]]


In [40]:
Y@X + Z@X

array([[ 58, 120,  31],
       [161, 167, 103],
       [ 88, 102,  55]])

In [41]:
(Y+Z) @ X  == Y@X + Z@X

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#### Property 5.  $A\cdot I = A$

In [42]:
X

array([[9, 3, 7],
       [4, 8, 1],
       [4, 6, 3]])

In [43]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
#For X at I
U = np.eye(3)

#first row of array 
xu_zero_by_zero_element = ((X[0,0] * U[0,0])+(X[0,1] * U[1,0])+(X[0,2]*U[2,0]))

xu_zero_by_one_element = ((X[0,0] * U[0,1])+(X[0,1] * U[1,1])+(X[0,2]*U[2,1]))

xu_zero_by_two_element = ((X[0,0] * U[0,2])+(X[0,1] * U[1,2])+(X[0,2]*U[2,2]))


#second row of array 
xu_one_by_zero_element = ((X[1,0] * U[0,0])+(X[1,1] * U[1,0])+(X[1,2]*U[2,0]))

xu_one_by_one_element = ((X[1,0] * U[0,1])+(X[1,1] * U[1,1])+(X[1,2]*U[2,1]))

xu_one_by_two_element = ((X[1,0] * U[0,2])+(X[1,1] * U[1,2])+(X[1,2]*U[2,2]))


#third row of array
xu_two_by_zero_element = ((X[2,0] * U[0,0])+(X[2,1] * U[1,0])+(X[2,2]*U[2,0]))

xu_two_by_one_element = ((X[2,0] * U[0,1])+(X[2,1] * U[1,1])+(X[2,2]*U[2,1]))

xu_two_by_two_element = ((X[2,0] * U[0,2])+(X[2,1] * U[1,2])+(X[2,2]*U[2,2]))


print(f'The product of X and I are:\n [{[xu_zero_by_zero_element, xu_zero_by_one_element, xu_zero_by_two_element]},\n {[xu_one_by_zero_element, xu_one_by_one_element, xu_one_by_two_element]},\n {[xu_two_by_zero_element, xu_two_by_one_element, xu_two_by_two_element]}]')

The product of X and I are:
 [[9.0, 3.0, 7.0],
 [4.0, 8.0, 1.0],
 [4.0, 6.0, 3.0]]


In [45]:
X @ np.eye(3)

array([[9., 3., 7.],
       [4., 8., 1.],
       [4., 6., 3.]])

In [46]:
X @ np.eye(3) == X

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#### Property 6.  $A\cdot \emptyset = \emptyset$ 

In [50]:
null_matrix = O
O = np.zeros((3,3))
print(O)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [52]:
#For Z at Null Matrix (O)

#first row of array 
zo_zero_by_zero_element = ((Z[0,0] * O[0,0])+(Z[0,1] * O[1,0])+(Z[0,2]*O[2,0]))

zo_zero_by_one_element = ((Z[0,0] * O[0,1])+(Z[0,1] * O[1,1])+(Z[0,2]*O[2,1]))

zo_zero_by_two_element = ((Z[0,0] * O[0,2])+(Z[0,1] * O[1,2])+(Z[0,2]*O[2,2]))


#second row of array 
zo_one_by_zero_element = ((Z[1,0] * O[0,0])+(Z[1,1] * O[1,0])+(Z[1,2]*O[2,0]))

zo_one_by_one_element = ((Z[1,0] * O[0,1])+(Z[1,1] * O[1,1])+(Z[1,2]*O[2,1]))

zo_one_by_two_element = ((Z[1,0] * O[0,2])+(Z[1,1] * O[1,2])+(Z[1,2]*O[2,2]))


#third row of array
zo_two_by_zero_element = ((Z[2,0] * O[0,0])+(Z[2,1] * O[1,0])+(Z[2,2]*O[2,0]))

zo_two_by_one_element = ((Z[2,0] * O[0,1])+(Z[2,1] * O[1,1])+(Z[2,2]*O[2,1]))

zo_two_by_two_element = ((Z[2,0] * O[0,2])+(Z[2,1] * O[1,2])+(Z[2,2]*O[2,2]))


print(f'The product of Z and Null Matrix are:\n [{[zo_zero_by_zero_element, zo_zero_by_one_element, zo_zero_by_two_element]},\n {[zo_one_by_zero_element, zo_one_by_one_element, zo_one_by_two_element]},\n {[zo_two_by_zero_element, zo_two_by_one_element, zo_two_by_two_element]}]')

The product of Z and Null Matrix are:
 [[0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0]]


In [54]:
Z @ O

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [53]:
Z @ O == O

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Conclusion

For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. Also answer the question: "how can matrix operations solve problems in healthcare?". 

In this lab activity, I familiarized the important concepts of matrix operations that are commonly used in Machine Learning. It is easier to do by inputting the matrix operations in Python scripts rather than computing it manually. It well explained the specific operations of each matrix operations given above and it made a sense of of the practical implementation of the matrix operation using Python and Jupyter Notebook. I conclude that, I achieved the interpretation of this lab activity and I performed it well. Hopefully, I found them helpful to gain a better understanding of the concept of matrix operations. 

In real-world data and solving problems when it comes in healthcare, it must be precise and accurate the output to get the absolute answer in order to find the possible solutions like for example of this pandemic. With the help of matrix operations, it is time-saving and computes efficiently wherever how big data it is.